package Paquetaxo;

import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;

/**
 *
 * @author Manuel
 */
public class Ventana extends javax.swing.JFrame {

    private final Operaciones OP;

    public Ventana() {
        setTitle("Listado de Procesos del Sistema");
        initComponents();
        OP = new Operaciones();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);

        getCell();
    }

    private void listar() {
        jtb_Tabla.setModel(OP.getDatos());
    }

    private void getCell() {
        ListSelectionModel cellSelectionModel = jtb_Tabla.getSelectionModel();
        cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                String selectedData = null;

                int[] selectedRow = jtb_Tabla.getSelectedRows();
                int[] selectedColumns = jtb_Tabla.getSelectedColumns();

                for (int i = 0; i < selectedRow.length; i++) {
                    for (int j = 0; j < selectedColumns.length; j++) {
                        // Pequeño truco
                        jtf_Fila.setText(""+selectedRow[i]);
                        if (selectedColumns[j] == 0 || selectedColumns[j] == 1) {
                            selectedData = (String) jtb_Tabla.getValueAt(selectedRow[i], selectedColumns[j]);
                            
                            
                        }
                    }
                }
                jtf_EliminarProceso.setText(selectedData);
                System.out.println(selectedData);
            }
        });       
    }

    private void crear() {
        boolean condicion = false;
        String nombre = "";
        String NomSesion = "";

        if (jtf_Nombre.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingresa un nombre");
        } else {
            nombre = jtf_Nombre.getText();
            condicion = true;
        }

        int PID = OP.makeRandom(1000);

        if (jrb_Console.isSelected()){
            NomSesion = "Console";
        } else if (jrb_Services.isSelected()){
            NomSesion = "Services";
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un Nombre de Servicio");
            condicion = false;
        }

        int NumSesion = OP.makeRandom(2);

        int Memoria = OP.makeRandom(100000);

        int Estado = OP.makeRandom(5);

        if (condicion == true) {
            String chorizo = "\"" + nombre + "\"," + "\"" + PID + "\"," + "\"" + NomSesion + "\"," + "\"" + NumSesion + "\","
                    + "\"" + Memoria + " KB\"," + "\"" + Estado + "\",";

            limpiarCajas();

            System.out.println(chorizo);

            OP.setDatos(chorizo);

        } else {
            // do nothing
        }

    }

    private void limpiarCajas() {
        jtf_Nombre.setText("");
        jrb_Console.setSelected(false);
        jrb_Services.setSelected(false);
    }

    private void descargar() {
        try {
            TableModel model = jtb_Tabla.getModel();
            PrintWriter out = new PrintWriter("ListaProcesos.csv");
            
            

            for (int i = 0; i < model.getColumnCount(); i++) {
                out.write(model.getColumnName(i) + ",");
            }

            out.write("\n");

            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    out.write(model.getValueAt(i, j).toString() + ",");
                }
                out.write("\n");
            }
            out.close();

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_Tabla = new javax.swing.JTable();
        btn_CargarProcesos = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        jtb_NuevoProceso = new javax.swing.JButton();
        jtf_Nombre = new javax.swing.JTextField();
        jtb_EliminarProceso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtf_EliminarProceso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jtb_Descargar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jtf_Fila = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jrb_Console = new javax.swing.JRadioButton();
        jrb_Services = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtb_Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtb_Tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtb_Tabla);

        btn_CargarProcesos.setText("Cargar Procesos");
        btn_CargarProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CargarProcesosActionPerformed(evt);
            }
        });

        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        jtb_NuevoProceso.setText("Nuevo Proceso");
        jtb_NuevoProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_NuevoProcesoActionPerformed(evt);
            }
        });

        jtb_EliminarProceso.setText("Eliminar Proceso");
        jtb_EliminarProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_EliminarProcesoActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre del Proceso");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtf_EliminarProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_EliminarProcesoActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre del Proceso a Eliminar");

        jtb_Descargar.setText("Descargar Lista de Procesos");
        jtb_Descargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_DescargarActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nombre de Sesión");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtf_Fila.setEnabled(false);
        jtf_Fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_FilaActionPerformed(evt);
            }
        });

        jrb_Console.setText("Console");
        jrb_Console.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_ConsoleActionPerformed(evt);
            }
        });

        jrb_Services.setText("Services");
        jrb_Services.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_ServicesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_CargarProcesos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_Nombre)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addComponent(jtf_Fila)
                            .addComponent(jtb_EliminarProceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_EliminarProceso)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtb_Descargar, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(jtb_NuevoProceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrb_Console)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrb_Services)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btn_CargarProcesos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jtf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrb_Console)
                            .addComponent(jrb_Services))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_NuevoProceso)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_Fila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_EliminarProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb_EliminarProceso)
                        .addGap(21, 21, 21)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtb_Descargar)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Salir)
                        .addGap(7, 7, 7)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        JOptionPane.showMessageDialog(this, "Programa hecho por: José Manuel Ruiz González \nGrupo: IC-502");
        this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void btn_CargarProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CargarProcesosActionPerformed
        listar();
        btn_CargarProcesos.setEnabled(false);
    }//GEN-LAST:event_btn_CargarProcesosActionPerformed

    private void jtb_EliminarProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_EliminarProcesoActionPerformed
        int index;
        String row = jtf_Fila.getText();
        index = Integer.parseInt(row);
        
        OP.deleteRow(index);
        JOptionPane.showMessageDialog(this,"Proceso Eliminado");
        descargar();
    }//GEN-LAST:event_jtb_EliminarProcesoActionPerformed


    private void jtf_EliminarProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_EliminarProcesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_EliminarProcesoActionPerformed


    private void jtb_DescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_DescargarActionPerformed
        descargar();
    }//GEN-LAST:event_jtb_DescargarActionPerformed

    private void jtb_NuevoProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_NuevoProcesoActionPerformed
        crear();
        descargar();
    }//GEN-LAST:event_jtb_NuevoProcesoActionPerformed

    private void jtf_FilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_FilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_FilaActionPerformed

    private void jrb_ConsoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_ConsoleActionPerformed
        jrb_Services.setSelected(false);
        jrb_Console.setSelected(true);
    }//GEN-LAST:event_jrb_ConsoleActionPerformed

    private void jrb_ServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_ServicesActionPerformed
        jrb_Services.setSelected(true);
        jrb_Console.setSelected(false);
    }//GEN-LAST:event_jrb_ServicesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error al aplicar el estilo al sistema", JOptionPane.ERROR_MESSAGE);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CargarProcesos;
    private javax.swing.JButton btn_Salir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JRadioButton jrb_Console;
    private javax.swing.JRadioButton jrb_Services;
    private javax.swing.JButton jtb_Descargar;
    private javax.swing.JButton jtb_EliminarProceso;
    private javax.swing.JButton jtb_NuevoProceso;
    private javax.swing.JTable jtb_Tabla;
    private javax.swing.JTextField jtf_EliminarProceso;
    private javax.swing.JTextField jtf_Fila;
    private javax.swing.JTextField jtf_Nombre;
    // End of variables declaration//GEN-END:variables
}
